<?php
/** @var \Ctasca\WmsSync\Block\Adminhtml\Product\Edit\Button\SyncWithWms\ClickHandler $block */
/** @var \Ctasca\WmsSync\ViewModel\WmsSync $viewModel */
$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();

if ($product !== null):
?>
<script type="text/x-magento-init">
    {
        "*": {
        "Ctasca_WmsSync/js/wms-sync":{
            "ajaxPostUrl" : "<?= $block->getUrl("wms/sync/index") ?>",
             "productSku" : "<?= $viewModel->getProduct()->getSku() ?>",
             "selectors" : {
                    "quantityInputName" : "product[quantity_and_stock_status][qty]",
                    "wmsSyncButtonId" : "#sync_with_wms"
                }
            }
        }
    }
</script>
<?php endif; ?>
